pipeline {
    agent any
    stages {
        stage('Clone Git repo') {
        steps {
            git branch: 'main', url: 'https://github.com/Kinamori/projet-poei.git'
              }
        }
        
        stage('Test : pytest'){        
        steps {
                sh '''
                    cd flask-pytest-example-master
                    pip3 install -r requirements.txt
                    pytest
                '''
          }
        }

    stage('Analyse code : Sonarqube') {
    steps {
    script {
       def scannerHome = tool 'Sonarqube Scanner';
           withSonarQubeEnv('Sonarqube'){
           sh " ${tool("Sonarqube Scanner")}/bin/sonar-scanner \
           -Dsonar.projectKey=projet_pipeline \
           -Dsonar.sources=. \
           -Dsonar.css.node=. 
               }
    }
           }
    }
    
        stage('Store Artefact : nexus'){        
        steps {
                sh '''
                    tar -czf archive$BUILD_NUMBER.tar.gz /var/jenkins_home/workspace/projet_pipeline
                    curl -v -u admin:root --upload-file /var/jenkins_home/workspace/projet_pipeline/archive$BUILD_NUMBER.tar.gz http://172.19.0.3:8081/repository/projet_pipeline/
                '''
          }

    }
}  
}
