pipeline {
    agent any
    stages {
        stage('Clone Git repo') {
        steps {
            git branch: 'main', url: 'https://github.com/Kinamori/projet-poei.git'
              }
        }
        
        stage('Test : pytest'){        
        steps {
                sh '''
                    cd flask-pytest-example-master
                    pip3 install -r requirements.txt
                    pytest
                '''
          }
        }

    stage('Analyse code : Sonarqube') {
    steps {
    script {
       def scannerHome = tool 'Sonarqube Scanner';
           withSonarQubeEnv('Sonarqube'){
           sh " ${tool("Sonarqube Scanner")}/bin/sonar-scanner \
           -Dsonar.projectKey=projet_pipeline \
           -Dsonar.sources=. \
           -Dsonar.css.node=. \
           -Dsonar.host.url=http://172.19.0.2:9000 \
           -Dsonar.login=933f34d817d7ef4b8b87944525c17b02c74d3743 \
           -Dsonar.exclusions=**/venv/**"
               }
    }
           }
    }
    
        stage('Store Artefact : nexus'){        
        steps {
                sh '''
                    cd /var/jenkins_home/workspace
                    rm -f archive*.tar.gz
                    tar -czvf archive$BUILD_NUMBER.tar.gz projet_pipeline
                    curl -v -u admin:root --upload-file archive$BUILD_NUMBER.tar.gz http://172.19.0.3:8081/repository/projet_pipeline/
                '''
          }

        }
        stage('Get Artefact : nexus') {
            steps {
                sh '''
                    cd /var/jenkins_home/prod/
                    curl http://172.19.0.3:8081/repository/projet_pipeline/archive$BUILD_NUMBER.tar.gz --output projet.tar.gz
                    tar xzvf projet.tar.gz
                    cd projet_pipeline
                    . /venv/bin/activate
                    cd deploy_project
                    ansible-playbook -i hosts.yaml script.yml
                '''
            }
        }
        stage('Deploy app : ansible') {
            steps {
                sh '''
                    cd /var/jenkins_home/prod/
                    tar xzvf projet.tar.gz
                    cd projet_pipeline
                    . /venv/bin/activate
                    cd deploy_project
                    ansible-playbook -i hosts.yaml script.yml
                '''
            }
        }
    }  
}
